### ISSUE TITLE
is it possible to add instructions for QNAP. 

### ISSUE THREAD

**Issue by Tdotsown** [Waterboy1602/Addarr#1]
is it possible to add instructions for QNAP.

**Comment by Waterboy1602** [comment]
This will be a bit hard, because I don't have a QNAP server in my surroundings and never have worked with one. If you could help me, I surely want to make a wikipage.

**Comment by Tdotsown** [comment]
How can I help. I’m not very technical

________________________________

**Comment by Waterboy1602** [comment]
How do you install services/apps on a QNAP server?

**Comment by Tdotsown** [comment]
The official ones from qnap App Store, I also have a repository for QNAPclub.eu and for plex I download it from online and instal it manually

________________________________

**Comment by Waterboy1602** [comment]
It's hard for me make a QPKG package without access to a QNAP server. I'm also not looking in the nearby future to buy a QNAP NAS server. Sorry that I cant help you

**Comment by Tdotsown** [comment]
It’s ok. Hopefully tech savvy someone with a QNAP can respond to this thread with a solution

________________________________

**Comment by toddrob99** [comment]
I suggest researching how to use Docker images/containers on QNAP. The provided Docker image should work on any platform that supports Docker. I don't have any QNAP devices, but a quick Google search turned up some results:

https://www.qnap.com/solution/container_station/en-us/
https://blog.linuxserver.io/2017/09/17/how-to-setup-containers-on-qnap/
https://www.reddit.com/r/qnap/comments/fa1dvy/tips_for_running_docker_containers_on_qnap/

It seems that QNAP has "Container Station" which is a QNAP-specific front-end for Docker, but you should also have the ability to use Docker CLI if you can SSH into your QNAP device. This is likely your best bet: SSH into your QNAP, use sudo or su to root to run `docker-compose up -d` in the Addarr app folder.
