### ISSUE TITLE
[Errno 29] Invalid seek

### ISSUE THREAD

**Issue by PosterHero** [Waterboy1602/Addarr#10]
New release won't work with docker:  see logging`Traceback (most recent call last):  File "/usr/src/addarr/addarr.py", line 5, in <module>    import sonarr as sonarr  File "/usr/src/addarr/sonarr.py", line 4, in <module>    import commons as commons  File "/usr/src/addarr/commons.py", line 10, in <module>    level=logging.INFO)  File "/usr/local/lib/python3.6/logging/__init__.py", line 1808, in basicConfig    h = FileHandler(filename, mode)  File "/usr/local/lib/python3.6/logging/__init__.py", line 1032, in __init__    StreamHandler.__init__(self, self._open())  File "/usr/local/lib/python3.6/logging/__init__.py", line 1061, in _open    return open(self.baseFilename, self.mode, encoding=self.encoding)OSError: [Errno 29] Invalid seek`

**Comment by Waterboy1602** [comment]
I don't really see where this error is coming from. I changed all the logfile locations to a variable, maybe this fixes the problem.

**Comment by Waterboy1602** [comment]
Closed, because of no response in one month.
