### ISSUE TITLE
TV Shows being added from bot as unmonitored?

### ISSUE THREAD

**Issue by BusterBlex** [Waterboy1602/Addarr#101]
Unsure if this is an issue with the config or in Sonarr itself but recently TV shows I have added are being added as unmonitored.

**Comment by Waterboy1602** [comment]
The same issue was just created yesterday (#100), but the author of the issue said it had something to do with his Sonarr instance.

I've tried it myself to add a TV Show and experienced the same issue: TV show was also added as unmonitored. I'm not yet sure if it really has something to do with Sonarr or if it is a bug in Addarr.

When I find the time, I'll look into this.

**Comment by BusterBlex** [comment]
Ok thanks, @Waterboy1602 will see if I can find any similar issues on my end as the author yesterday.

**Comment by Waterboy1602** [comment]
I've added at the PUT-request to Sonarr when adding a TV Show: `"monitored": True`. Now they are added again as Monitored. I have no clue what changed at Sonarr's side, but at least it's working again.

**Comment by BusterBlex** [comment]
Hey @Waterboy1602 just checking how I update this for a synology docker instance? I've tried change the config file and updating the docker registery but haven't had any luck fixing this. Probably missing something as I am a bit of a novice.
