### ISSUE TITLE
Cant download

### ISSUE THREAD

**Issue by mixxit** [Waterboy1602/Addarr#11]
Hi couple of questions

I cant seem to get anything to add to radarr after the 'Yes, add this movie' 

I am not 100% sure on what im supposed to set as the path, is this the path to where i keep my media after radarr has finished downloading?

**Comment by Waterboy1602** [comment]
If you don't get a respons after 'Yes, add this movie', it means the bot can't connect with Radarr. You sure your config settings are correct?

The rootFolder config is the path where the media is placed after downloading.

**Comment by Waterboy1602** [comment]
Closed, because of no response in one month.
