### ISSUE TITLE
Cannot add series on sonarr v4 because of language profile

### ISSUE THREAD

**Issue by memnos** [Waterboy1602/Addarr#138]
Hello, i've upgraded my sonarr to v4 and now i cannot add any series via addarr.
My config is:
sonarr:
  server:
    addr: *.*.*.*
    port : **** # Default is 8989
    path: / # Default is / . If set, it must start and finish with / . Eg: /son>
    ssl: false #default false
  auth:
    apikey: ****************************
    username: *********
    password: ********
  search: true
  seasonFolder: true
  languageProfile: Italian
  excludedRootFolders: # If set must not have a trailing slash Eg: /mnt/Media
    - # First excluded folder, add others with a "-" on a new line (same indent>
  excludedQualityProfiles:
    -
  defaultTags: # If set must be existing tags
    - telegram
  adminRestrictions: false

The log is:
addarr.sonarr - DEBUG - Didn't find a match with languageProfile from the config file. Took instead the first languageId from languageProfile-API response

What can i do?
Tnx

**Comment by Waterboy1602** [comment]
Is this already fixed or does this issue still exists?

**Comment by spiveym** [comment]
@Waterboy1602 i'm still getting the same error as above, even though i'm pulling:

> image: waterboy1602/addarr:latest

> 2024-01-09 16:58:46,662 - addarr.sonarr - DEBUG - Didn't find a match with languageProfile from the config file. Took instead the first languageId from languageProfile-API response

Language prefs are the same as the example config.yaml. Any clue as to why i'm still getting the error, please?

**Comment by Waterboy1602** [comment]
You can't use the languageProfile anymore. It got removed in the latest API version.

Are you sure that you're using the latest version of Addarr, because in the latest version you should not have got that DEBUG message? The code that generates that DEBUG message has been removed.
