### ISSUE TITLE
Docker not starting

### ISSUE THREAD

**Issue by perikin88** [Waterboy1602/Addarr#141]
Since the latest docker image, pushed 2 days ago on the 24th of September, the container doesn't start.
I can see the following error: 
`Traceback (most recent call last):
  File "/app/src/addarr.py", line 6, in <module>
    from telegram import InlineKeyboardButton, InlineKeyboardMarkup, Update, ParseMode
ImportError: cannot import name 'ParseMode' from 'telegram' (/usr/local/lib/python3.11/site-packages/telegram/__init__.py)`

Do you know what could be the problem here?

Thanks in advance!

**Comment by Waterboy1602** [comment]
I see that there were a lot of breaking changes in the latest version of (Python Telegram Bot)[https://github.com/python-telegram-bot/python-telegram-bot]. I'll need to make some changes in the code to let it work with the latest version

**Comment by perikin88** [comment]
Thank you!
Maybe useful for others in the same situation. It is still possible to access the previous docker image:
`waterboy1602/addarr@sha256:7b8e178ec9c3a69f3799963f35a65c6ee06c97339110da3551bdbf7280bfc27b`

**Comment by Waterboy1602** [comment]
I've released a new version of Addarr ([V0.7](https://github.com/Waterboy1602/Addarr/releases/tag/V0.7)). With this release I hope that all the breaking changes that brought V20 of the Python Telegram Bot with it, are fixed. 

Let me know, if it still isn't working. Hereby I'll also close this issue.

**Comment by ANS-spb** [comment]
The different error causes with new release:

**Comment by Waterboy1602** [comment]
There were some problems with the latest Python version (3.11.5) that I didn't notice. I've made some changes to the code and think that these now are resolved. 

Could you try them then on your machine? The latest Docker image already contains the bugfixes.

**Comment by ANS-spb** [comment]
It works, thank you very much!
