### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by jjscaria** [Waterboy1602/Addarr#142]
I am not able to authenticate the bot. Whenever I try to authenticate I get `You entered the wrong password. Try again...` message and I am seeing the following in the logs:
```
No error handlers are registered, logging exception.

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_application.py", line 1184, in process_update

    await coroutine

  File "/usr/local/lib/python3.11/site-packages/telegram/ext/_basehandler.py", line 141, in handle_update

    return await self.callback(update, context)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/src/commons.py", line 92, in authentication

    file.write(getChatName(context, chatid))

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/src/commons.py", line 111, in getChatName

    if chat.username:

       ^^^^^^^^^^^^^

AttributeError: 'coroutine' object has no attribute 'username'
```

Installed using Docker

**Comment by seanm581** [comment]
I'm getting the same error too, just installing for the first time though

**Comment by Waterboy1602** [comment]
This was something I overlooked while fixing Addarr for the latest Python Telegram Bot version. Should be fixed with the latest commit [ff95ef1](https://github.com/Waterboy1602/Addarr/commit/ff95ef1fe41d1f45ebaed2416c64afdbdf0ab16d).

**Comment by seanm581** [comment]
thank you!
Any reason why I would get this error?
IsADirectoryError: [Errno 21] Is a directory: '/app/config.yaml'
Traceback (most recent call last):
File "/app/src/addarr.py", line 15, in <module>
from commons import checkAllowed, checkId, authentication, format_bytes, getAuthChats
File "/app/src/commons.py", line 5, in <module>
from config import config
File "/app/src/config.py", line 5, in <module>
config = yaml.safe_load(open(CONFIG_PATH, encoding="utf8"))

**Comment by seanm581** [comment]
Thank you! It's working again, but my bot only replies back with "this chat is already authorized". What does this mean?

**Comment by jjscaria** [comment]
Working now. Thank you for the fix!
