### ISSUE TITLE
qualityProfileId

### ISSUE THREAD

**Issue by tulkarxxx** [Waterboy1602/Addarr#15]
Hi, how can I get the list of equivalent values?
For example,. what is the righ value for 1080p  ?

Thanks

**Comment by Waterboy1602** [comment]
If you want to let Sonarr only download 1080p files, you should make a profile in Sonarr itself. Profiles are default numbered. You should change the number that is given in `config.yaml` to your corresponding profile.

**Comment by tulkarxxx** [comment]
Yes, I have like 7 profiles created, but with names "720p", "1080p", etc, I don,t know how to get the equivalent number for every profile

Best regards

**Comment by Waterboy1602** [comment]
You could perform an API request as you can read [here](https://github.com/Sonarr/Sonarr/wiki/Profile). You will get a JSON respons with all your profiles and also their id.

An example of such a request is: `https://localhost:8989/api/profile?apikey=YOUR_API_KEY`

**Comment by tulkarxxx** [comment]
Perfect!!
Thanks a lot

**Comment by Waterboy1602** [comment]
I will close this issue as it's been solved.
