### ISSUE TITLE
Problem adding series at season selection

### ISSUE THREAD

**Issue by nithou** [Waterboy1602/Addarr#150]
I tried to add a series (Suits) through the bot but it seems that since the new multiple season selector it crashes. I can search the serie, but just after selecting "All seasons", the bot stop responding.

The logs show this:

> 
> No error handlers are registered, logging exception.
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/lib/python3.11/site-packages/telegram/ext/_application.py", line 1234, in process_update
> 
>     await coroutine
> 
>   File "/usr/local/lib/python3.11/site-packages/telegram/ext/_conversationhandler.py", line 857, in handle_update
> 
>     new_state: object = await handler.handle_update(
> 
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/telegram/ext/_basehandler.py", line 157, in handle_update
> 
>     return await self.callback(update, context)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/app/src/addarr.py", line 772, in checkSeasons
> 
>     await context.bot.edit_message_text(
> 
>   File "/usr/local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 1473, in edit_message_text
> 
>     return await super().edit_message_text(
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 525, in decorator
> 
>     result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
> 
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 3288, in edit_message_text
> 
>     return await self._send_message(
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 522, in _send_message
> 
>     result = await super()._send_message(
> 
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 703, in _send_message
> 
>     result = await self._post(
> 
>              ^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 613, in _post
> 
>     return await self._do_post(
> 
>            ^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 340, in _do_post
> 
>     return await super()._do_post(
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/telegram/_bot.py", line 641, in _do_post
> 
>     return await request.post(
> 
>            ^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 200, in post
> 
>     result = await self._request_wrapper(
> 
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 379, in _request_wrapper
> 
>     raise BadRequest(message)
> 
> telegram.error.BadRequest: Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
> 
> No error handlers are registered, logging exception.
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/lib/python3.11/site-packages/telegram/ext/_application.py", line 1234, in process_update
> 
>     await coroutine
> 
>   File "/usr/local/lib/python3.11/site-packages/telegram/ext/_conversationhandler.py", line 857, in handle_update
> 
>     new_state: object = await handler.handle_update(
> 
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/telegram/ext/_basehandler.py", line 157, in handle_update
> 
>     return await self.callback(update, context)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/app/src/addarr.py", line 746, in checkSeasons
> 
>     return await addSerieMovie(update, context)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/app/src/addarr.py", line 817, in addSerieMovie
> 
>     service.createTag(str(update.effective_message.chat.id))
> 
>   File "/app/src/sonarr.py", line 161, in createTag
> 
>     "id": max([t["id"] for t in getTags()])+1,
> 
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> ValueError: max() arg is an empty sequence

**Comment by Waterboy1602** [comment]
I think that I've located the bug and fixed it. I'll close this issue for now
