### ISSUE TITLE
addarr does not raise from synology

### ISSUE THREAD

**Issue by edupufpuf** [Waterboy1602/Addarr#154]
When I try to run docker container, i have the below error:

FileNotFoundError: [Errno 2] No such file or directory: '/app/config.yaml'

My config file:

# Sonarr Configuration
sonarr:
  server:
    addr: 192.168.0.xx
    port : 8989 # Default is 8989
    path: /docker/sonarr/ # Default is / . If set, it must start and finish with / . Eg: /sonarr/
    ssl: false # Default false
  auth:
    apikey: xxxxxxxx
    username: xxxxxxxx
    password: xxxxxxx
  search: true # Start search after adding series
  seasonFolder: true
  languageProfile: English
  excludedRootFolders: # If set must not have a trailing slash Eg: /mnt/Media
    - # First excluded folder, add others with a "-" on a new line (same indentation)
  narrowRootFolderNames: true # If true, only the last folder name will be shown instead of full path
  excludedQualityProfiles:
    - 
  defaultTags: # If set must be existing tags
    - telegram
  addRequesterIdTag: true # Add telegram user id as tag on series
  adminRestrictions: false

# Radarr Configuration
radarr:
  server:
    addr: 192.168.0.xx
    port : 7878 # Default is 7878
    path: /docker/radarr/ # Default is / . If set, it must start and finish with / . Eg: /radarr/
    ssl: false # Default false
  auth:
    apikey: xxxxxxx
    username: xxxx
    password: xxxxx  # Start search after adding movie
  search: true
  minimumAvailability: announced
  excludedRootFolders: # If set must not have a trailing slash Eg: /mnt/Media
    - # First excluded folder, add others with a "-" on a new line (same indentation)
  narrowRootFolderNames: true #If true, only the last folder name will be shown instead of full path
  excludedQualityProfiles:
    - 
  defaultTags: # If set must be existing tags
    - telegram
  addRequesterIdTag: true # Add telegram user id as tag on movie
  adminRestrictions: false
  
# Telegram Configuration
telegram:
  token: xxxx
  password: xxxxx

# Transmission Configuration
transmission:
  enable: true # Enable the Transmission commands
  onlyAdmin: true # Transmission command  will only work for admins
  host: 192.168.0.18:9091 # IP-adres of the Transmission service
  authentication: true # Is Transmission protected with a password?
  username: xxxxxxx
  password: xxxxxxx

sabnzbd:
  enable: true
  onlyAdmin: true
  server:
    addr:
    port: 8090 # Default is 8090
    path: / # Default is / . If set, it must start and finish with / . Eg: /sonarr/
    ssl: false # Default false
  auth:
    apikey:
    username:
    password:

# Optional settings:
## Language
language: es-es # de-de, en-us, es-es, fr-fr, it-it, nl-be, pl-pl, pt-pt, ru-ru

## Entrypoints
entrypointAuth: auth # auth or a custom entrypoint
entrypointHelp: help # help entrypoint
entrypointAdd: start # start or a custom entrypoint
entrypointAllSeries: allSeries # allSeries or a custom entrypoint
entrypointAllMovies: allMovies # allMovies or a custom entrypoint
entrypointTransmission: transmission # transmission or a custom entrypoint
entrypointSabnzbd: sabnzbd # sabnzbd or a custom entrypoint

## Restrict some commands to only admins and/or provide extra authorization by usernames
enableAdmin: false # Check admin.txt
enableAllowlist: false # Check allowlist.txt - very restrictive!

## Logging
logToConsole: true
debugLogging: false
adminNotifyId:

**Comment by Waterboy1602** [comment]
Have you linked your `config.yaml`-file in the `docker-compose.yml`? As is described in [this wiki](https://github.com/Waterboy1602/Addarr/wiki/Installation-on-Docker):

>     volumes:
>     - ./config.yaml:/app/config.yaml:ro
>     - ./chatid.txt:/app/chatid.txt:rw
>     - ./admin.txt:/app/admin.txt:ro
>     - ./logs:/app/logs:rw

**Comment by edupufpuf** [comment]
thanks a lot for your support. 

I didn't do the step you indicated. I followed the tutorial for synology. From this link --> https://github.com/Waterboy1602/Addarr/wiki/Installation-on-Synology-(Docker)

**Comment by Waterboy1602** [comment]
I'm glad I could help. I'll close this issue as it has been resolved.
