### ISSUE TITLE
Large pull request for coding standards?

### ISSUE THREAD

**Issue by toddrob99** [Waterboy1602/Addarr#20]
Hello. I am a hobbyist python developer with a few significant projects under my belt ([MLB-StatsAPI](https://github.com/toddrob99/MLB-StatsAPI) being the most utilized and [redball](https://github.com/toddrob99/redball) being the largest). I also developed and run several bots for work that are in private repos, although I am new to developing bots for Telegram.

I have forked your repo and made some significant changes to code formatting, while not actually changing functionality. Before submitting a pull request I thought I would ask if you are open to this level of change from a community member.

The only end-user-visible changes I made are in lang.yaml, where I changed "serie" to "series" in the English section, fixed a grammatical error, and removed reference to Plex since being added to Sonarr/Radarr does not equate to being downloaded and available in Plex.

Please review the [commit](https://github.com/toddrob99/Addarr/commit/433cda29f7bbc69064ba40f253113c1e58a1750a) on my dev branch and let me know if you are interested in me submitting a pull request.

As a side note, I also plan to look into adding support for multiple root paths in Sonarr and Radarr, since I don't want everything to be added to the default. It will be difficult to submit pull requests for new functionality if we are not using the same standards (I've applied black for formatting and flake8 for linting).

**Comment by Waterboy1602** [comment]
Thank you al lot for the interest in my project! I'm always happy when I see that someone else is interested in the work that I'm delivering.

I'm have no problem at all with your changes. I've reviewed your commit and it was directly clear to me that code was a lot better readable. You should make your pull request and I will accept it.

Thanks for fixing the grammatical errors! As you probably could read, is English not my native language. So sooner or later I surely will make some language errors. Thanks for pointing them out.

For the moment I'm not so used at using standards, but I understand that it's necessary to have standards when you work at the same code. I will look into them and start using it.

As you may have seen, there are already some users that made feature requests. I will look into them to see whats possible to do with those, but it's always easier if you can work at them with different people. That would let the development go a lot faster.
