### ISSUE TITLE
Bot does not support concurrent users

### ISSUE THREAD

**Issue by toddrob99** [Waterboy1602/Addarr#22]
If two users try to interact with the bot at the same time, the global `service` and `output` vars get conflicted. A possible solution (which would require only minimal code changes) is to assign a unique session id when a user starts the process, and move `service` and `output` into a dict using the session id as the key. For example:

``` python
sessionData = {
    "UNIQUE-SESSION-ID": {
        "service": None,
        "output": None,
    },
    "ANOTHER-UNIQUE-SESSION-ID": {
        "service": None,
        "output": None,
    },
}
```

I've been learning more about the python-telegram-bot module, and the best solution for this might be as easy as moving the service and output variables inside `context.user_data`.

I am willing to work on adding support for concurrency, if you want. Feel free to assign the issue to me.

**Comment by toddrob99** [comment]
I solved this issue by adding the `getService()` method that uses `context.user_data["choice"]` to derive `service`, and by moving `output` to `context.user_data["output"]`.

**Comment by eymericguyot** [comment]
This doesnt seem to be working anymore as I am having concurrency issues right now

**Comment by jpalanca** [comment]
Might be having the same issue. My bot keeps asking for a password and then only replies with
`This chat is already authorized.`

**Comment by Waterboy1602** [comment]
This normally has nothing to do with the concurrency problem. Could you try completely reinstalling the bot? To be honest I've not yet heard of this problem.
