### ISSUE TITLE
Clarify Docker installation guide

### ISSUE THREAD

**Issue by Waterboy1602** [Waterboy1602/Addarr#25]
@toddrob99 I saw that you edited the [Docker installation guide](https://github.com/Waterboy1602/Addarr/wiki/Installation-on-Docker). 

Could you maybe clarify it a bit more? I just transferred from FreeBSD to Docker and I didn't even succeed in installing my own project. I struggled at the step where you should rename `config-example.yml` to `config.yml`. How are you supposed to do this? I can't find this files or better said: I have no idea where these files are supposed to be.

I already thank you a lot for the work you've put in this project!

**Comment by toddrob99** [comment]
Done

**Comment by toddrob99** [comment]
@Waterboy1602, if you want to test the version that includes the changes in #24, just change the image in `docker-compose.yml` from `image: waterboy1602/addarr` to `image: toddrob/addarr` and then `docker-compose up -d`.

**Comment by Waterboy1602** [comment]
Thanks!! I succeeded in testing your docker image. The update of the wiki page made the installation a lot easier.
