### ISSUE TITLE
Better handling of "no result found"

### ISSUE THREAD

**Issue by frdmn** [Waterboy1602/Addarr#26]
When there is no movie found, the bot responds like this:

<img width="387" alt="Bildschirmfoto 2020-07-09 um 07 42 31" src="https://user-images.githubusercontent.com/944459/87001496-e39b4080-c1b7-11ea-811e-035db67f05df.png">

A proper error message would be nice here to indicate that there are actually no results for the given search term.

**Comment by Waterboy1602** [comment]
Fixed with latest commit: [8ecd766
](https://github.com/Waterboy1602/Addarr/commit/8ecd766a27199ad58a7a4e247cc5d9d5a337b49f)

**Comment by frdmn** [comment]
@Waterboy1602 Well done! 🎉
