### ISSUE TITLE
Command to request series list in sonarr

### ISSUE THREAD

**Issue by tulkarxxx** [Waterboy1602/Addarr#28]
HI, this is not an issue, is a request, will be possible to have a new command to retrieve a list with existing sonarr series?

Thanks

**Comment by Waterboy1602** [comment]
How do you exactly see this feature? Do you see it as large text message with all the series? Or do you have an other idea about this?

**Comment by tulkarxxx** [comment]
Yes, a large text with one row per tv show will be nice, also sorted by tittle
Thanks

**Comment by tulkarxxx** [comment]
Also if additional info per tittle could be showed in same row will be increbible, like monitored , progress, or  ended,

**Comment by Waterboy1602** [comment]
I've added the feature with commit [ef096da](https://github.com/Waterboy1602/Addarr/commit/ef096da675e799376f4b997b210f4b9504415f36). I've also made a new release that adds this feature together with some other bugfixes.
