### ISSUE TITLE
Download status

### ISSUE THREAD

**Issue by keteague** [Waterboy1602/Addarr#32]
Would it be possible to check Activity > Queue for when an item begins downloading and send a notification in Telegram?... then when the item is done downloading and send another notification?

And maybe another separate command to poll Activity > Queue to see the status of where a download is while in progress?

**Comment by pxn4** [comment]
@keteague you can try embedded radarr/sonarr feature that doing exact same thing.
You can found it under **Settings > Connections > Telegram**
This is [how](https://prnt.sc/vyvmrd) it looks like

**Comment by Waterboy1602** [comment]
After no comment of @keteague and a perfect solution for this feature request, I will close this issue. 

Addarr is only made to add new movies/series to Radarr/Sonarr. I won't be looking into making a feature to follow the download status as you can perfectly do that with the build in feature of Raddarr and Sonarr.
