### ISSUE TITLE
Custom keyboard remains after flow is completed

### ISSUE THREAD

**Issue by toddrob99** [Waterboy1602/Addarr#34]
The custom keyboard continues to pop up after the flow has ended. I suggest including `reply_markup=telegram.ReplyKeyboardRemove()` with the 'End' message in stop(), to remove the custom keyboard.

**Comment by Waterboy1602** [comment]
Thanks for the suggestion! I've added it with this commit: [b1fa502](https://github.com/Waterboy1602/Addarr/commit/b1fa5022a7a8ff75cfd1821f02c7b8ba1fe6acb9).
