### ISSUE TITLE
Identify authenticated users by name

### ISSUE THREAD

**Issue by jtrosper** [Waterboy1602/Addarr#35]
Feature request: Have the user's Telegram name or username be identified in the auth file, so that revocation can be done easily.

**Comment by Waterboy1602** [comment]
Added to the latest release [V0.6](https://github.com/Waterboy1602/Addarr/releases/tag/V0.6)

**Comment by Waterboy1602** [comment]
Added to the latest release [V0.6](https://github.com/Waterboy1602/Addarr/releases/tag/V0.6)
