### ISSUE TITLE
Start command not unique

### ISSUE THREAD

**Issue by eymericguyot** [Waterboy1602/Addarr#41]
The /start in a gorup starts questions for every user in the group instead of the one that started the command making weird interactions when people come check the messages or are already in chat.

**Comment by Waterboy1602** [comment]
This was normally fixed with #22. I'll look into this after my exams. Feel free to make a PR in the meantime if you fixed the problem yourself.

**Comment by eymericguyot** [comment]
Hello :),  any news on this?

**Comment by Waterboy1602** [comment]
I've not yet found the time to look into this. It will be the next thing I fix.
