### ISSUE TITLE
Typing start without the command slash "/" still starts the program even in long sentences

### ISSUE THREAD

**Issue by eymericguyot** [Waterboy1602/Addarr#42]
Example: 
Me: "Yeah i'm gonna start the server now" or "Cool i cant wait to start watching that show i heard great things about it!"
Adaar Bot: "Enter movie name:"

I dont think it should be working this way as it is not conveniant especially when there is no way to cancel the command until you've searched for a movie name which i think is another issue.

**Comment by Waterboy1602** [comment]
That's indeed now how it's supposed to be. This is something easy to fix. I will also look into this after my exams ;)
