### ISSUE TITLE
Ability to select quality? 720, 1080,4K...

### ISSUE THREAD

**Issue by chriskob** [Waterboy1602/Addarr#49]
Any possibility to get the bot to ask what quality is wanted?

Thanks and nice work on this.

**Comment by skynet01** [comment]
Would love this as well :)

**Comment by dusanzk** [comment]
This would be very useful

**Comment by Waterboy1602** [comment]
Added to the latest release [V0.6](https://github.com/Waterboy1602/Addarr/releases/tag/V0.6)
