### ISSUE TITLE
Sonarr: Oops, failed to add the series. Maybe give it another try.

### ISSUE THREAD

**Issue by Sloth-on-meth** [Waterboy1602/Addarr#50]
Hi!

I'm not getting any errors in the log, but adding series to sonarr does not work. 

```root@skynetbams:/docker# docker-compose up addarr
Starting addarr ... done
Attaching to addarr
addarr          | /usr/local/lib/python3.9/site-packages/telegram/ext/conversationhandler.py:279: UserWarning: If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
addarr          |   warnings.warn(
addarr          | 2021-02-11 11:24:59,005 - addarr - INFO - Start chatting with Addarr in Telegram. The first time you use "start" you will be asked to enter your password.```

**Comment by Waterboy1602** [comment]
Could you recheck your `config.yaml` or put it here (with the API keys removed)? This most of the time means that there is something wrong in your config.

**Comment by Sloth-on-meth** [comment]
Yes, will do!

**Comment by ywattenberg** [comment]
I have the same issue let me know if you found a solution. Same config is work for radarr though.

**Comment by Waterboy1602** [comment]
@ywattenberg It's hard to tell whats wrong with your `config.yaml` file, if we dont have your config. For me it still works to add series to Sonarr

**Comment by ywattenberg** [comment]
I basically used the default config here: 
[config.yaml.txt](https://github.com/Waterboy1602/Addarr/files/6020551/config.yaml.txt)
It seems to work to some extend as i get to the point of choosing the root dic for the series but after that the adding the series fails.
I already checked the ports, API keys and Addr vars.
