### ISSUE TITLE
I want to translate into Russian

### ISSUE THREAD

**Issue by olegosipenko87** [Waterboy1602/Addarr#58]
Hello

Thanks for the bot. I want to translate it into Russian, but there were some difficulties.
Editing lang.yaml, but the bot stops working on several of the lines:

```
    Start: Start  - does not work if I change
    Stop: Stop  - does not work
    Movie: Film  - does not work
    Serie: Series  - does not work
    End: Добавление фильма или сериала прекращено.  - working
```

I can't understand what it depends on

**Comment by Waterboy1602** [comment]
I don't totally get the problem. What does the bot still do or doesn't do it after adding the Russian translation? Do you mean that the message are still in English? Or do you mean that some commands don't work anymore?

**Comment by olegosipenko87** [comment]
if i change:
```
en:
    Start: Start
    Stop: Stop
    Movie: Фильм
    Serie: Series
```

i get this error when bot starts
```
pi@raspberrypi:/opt/addarr $ python3 addarr.py
Traceback (most recent call last):
  File "addarr.py", line 551, in <module>
    main()
  File "addarr.py", line 62, in main
    CommandHandler(transcript["Movie"], startSerieMovie),
  File "/usr/local/lib/python3.7/dist-packages/telegram/ext/commandhandler.py", line 162, in __init__
    raise ValueError('Command is not a valid bot command')
ValueError: Command is not a valid bot command
```

**Comment by olegosipenko87** [comment]
and there is another error.
if i change:
```
en:
    Start: Start
    Stop: Стоп
    Movie: Movie
    Serie: Series
```
the bot starts normally, but the **stop** button does not work when communicating with the bot. No reaction to her

**Comment by Waterboy1602** [comment]
I've found this in the Telegram docs about the [CommandHandler ](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.commandhandler.html) function:
> Raises     ValueError - when command is too long or has illegal chars. –

I have a feeling this has something to do with it. The weird part is that I can nowhere find which chars are defined as illegal, but I assume those Russian chars are. I fear there is no other solution then to keep using the English commands. 

You can still translate the other lines in Russian, altough I understand that's not everything.
