### ISSUE TITLE
Provide automatically build image on docker hub

### ISSUE THREAD

**Issue by schoentoon** [Waterboy1602/Addarr#6]
As you're already providing a Dockerfile anyway, it might be worth it to simply set up automated builds on docker hub. This way people can just `docker pull` it and try it out right away without having to build the image themselves first. Documentation for this can be found [here](https://docs.docker.com/docker-hub/builds/). Or simply login on https://hub.docker.com/ create a repository, link github and it should be fairly straight forward from there.

**Comment by Waterboy1602** [comment]
All the credits for the Dockerfile go to @tedvdb. So maybe he can set this up, because I don't have any experience with docker.

**Comment by schoentoon** [comment]
Pretty sure only the repository owner can set automatic building up sadly, otherwise I would already have done so myself.

**Comment by Waterboy1602** [comment]
It assume it works: [addarr docker](https://hub.docker.com/r/waterboy1602/addarr). Could you look into it if it's alright?

**Comment by schoentoon** [comment]
Did you happen to have deleted the image tagged latest in favor for a tagged version? :thinking: This break a `docker pull waterboy1602/addarr` as it'll default to the image tagged latest at all times.

**Comment by Waterboy1602** [comment]
That's something I didn't know. I just thought it was nicer with this tagged version. I will change it again.
