### ISSUE TITLE
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries  

### ISSUE THREAD

**Issue by juanra** [Waterboy1602/Addarr#64]
Pulling docker addarr (waterboy1602/addarr:) give me this error.  Using a RPi 4.

**Comment by Waterboy1602** [comment]
Can it be because the docker builds are only built for amd64 and arm64? Otherwise I have no idea.

I've already been reported in the past that you can install Addarr on a RPi 4 by using [this wiki](https://github.com/Waterboy1602/Addarr/wiki/Installation-on-Linux), instead of using Docker.

**Comment by juanra** [comment]
I fix this adding this in my docker-compose file:

platform: linux/x86_64

But now I am getting these errors :

standard_init_linux.go:219: exec user process caused: exec format error,
standard_init_linux.go:219: exec user process caused: exec format error,
standard_init_linux.go:219: exec user process caused: exec format error,
standard_init_linux.go:219: exec user process caused: exec format error,
standard_init_linux.go:219: exec user process caused: exec format error,
standard_init_linux.go:219: exec user process caused: exec format error,
standard_init_linux.go:219: exec user process caused: exec format error,
standard_init_linux.go:219: exec user process caused: exec format error,
standard_init_linux.go:219: exec user process caused: exec format error,
standard_init_linux.go:219: exec user process caused: exec format error,
standard_init_linux.go:219: exec user process caused: exec format error,
standard_init_linux.go:219: exec user process caused: exec format error,
standard_init_linux.go:219: exec user process caused: exec format error,
standard_init_linux.go:219: exec user process caused: exec format error,
standard_init_linux.go:219: exec user process caused: exec format error,
standard_init_linux.go:219: exec user process caused: exec format error,

**Comment by juanra** [comment]
Apparently it was only necessary to compile the docker image for an arm7 architecture (I followed the steps described [here](https://github.com/perara/wg-manager/issues/69)). 

Due to access issues I couldn't upload it to your repository so I uploaded it to mine.

Anyone who wants to use the docker container in RPi can put:

image: juanra / addarr-rpi: armv7l-latest

**Comment by Waterboy1602** [comment]
Could you try again to pull my Docker Addarr image? I've added the linux/arm platform to the Docker build action, so I assume this should fix the problem.

**Comment by Waterboy1602** [comment]
Inactive
