### ISSUE TITLE
Getting "AttributeError: module 'i18n' has no attribute 'load_path'" on Pi4

### ISSUE THREAD

**Issue by skynet01** [Waterboy1602/Addarr#66]
After the latest update i can no longer start Addarr getting the following error:

```
Traceback (most recent call last):
  File "addarr.py", line 11, in <module>
    from commons import checkId, authentication, format_bytes, format_long_list_message
  File "/home/pi/Addarr/commons.py", line 7, in <module>
    from translations import i18n
  File "/home/pi/Addarr/translations.py", line 6, in <module>
    i18n.load_path.append(LANG_PATH)
AttributeError: module 'i18n' has no attribute 'load_path'
```

**Comment by skynet01** [comment]
Found the issue, the issue is that new update requires "python-i18n" library and not the "i18n" library which is the error that you would get at first so installing i18n would result in the issue above. There should be a note somewhere that "pip install -r requirements.txt" or whatever the command for your os is needs to execute after each update. 

...Anyway running 

```
pip uninstall i18n
```
followed by 
```
pip install -r requirements.txt
```
fixed the issue for me

**Comment by anewlearner256** [comment]
i got this problem:
`AttributeError: module 'sphinx.util' has no attribute 'i18n'`
