### ISSUE TITLE
if you have multiple volumes attached they all show same free size 

### ISSUE THREAD

**Issue by skynet01** [Waterboy1602/Addarr#67]
There seems to be a bug when you select file path it doesn't show the space for volumes correctly. I have multiple mounted external drives and i always get the same size for all of them:

![image](https://user-images.githubusercontent.com/8117544/116009063-4be2d380-a5cc-11eb-8fbf-a6335e22775b.png)

**Comment by anast20sm** [comment]
It seems to be related to sonarr/radarr. This info is taken directly from API's json response (check https://radarr.video/docs/api/#/Root%20Folder/get-rootfolder to see it)

**Comment by Waterboy1602** [comment]
As this isn't a problem that has to do with Addarr, I'm going to close this issue
