### ISSUE TITLE
No results with search

### ISSUE THREAD

**Issue by MattBlacKK85** [Waterboy1602/Addarr#7]
Hi, i'm using docker. After the /start command i will get the question of the bot but when i'm answer with movie or show it won't reply

in the log of the docker i don't see anything except Start chatting with....

example of my config.yaml

sonarr:
    server:
        addr: http://172.18.0.1
        port: 8989
        ssl: false
    auth:
        apikey: 818xxxxxxxxxx
        username: 
        password: 
    search: true
    rootFolder: /tv
    seasonFolder: true
    qualityProfileId: 1

**Comment by Waterboy1602** [comment]
Have you checked the log file? The bot should make a logfile when there happen some errors. It's hard for me to find the problem without the files.

**Comment by MattBlacKK85** [comment]
Where would this be located. It’s not in the folder.

Op 13 jan. 2020 om 22:09 heeft Wannes Van de Putte <notifications@github.com> het volgende geschreven:

﻿

Have you checked the log file? The bot should make a logfile when there happen some errors. It's hard for me to find the problem without the files.

**Comment by Waterboy1602** [comment]
I was thinking: you sure you can access your sonarr/adarr service?

Normally when the python script is started, there should be made a file named _telegramBot.log_. 

I've read this in the Dockerfile: `symlink to redirect logs to stdout`. I assume this means that everything from the logfile can be found back in the docker logs. It's strange there's nothing in there

**Comment by MattBlacKK85** [comment]
The logging in docker wasn't showing errors. I wasn't getting reply's because my bot wasn't able to read messages... after that it couldn't add shows/movies because the qualityprofile id was wrong. 

It's working now! thanks
