### ISSUE TITLE
Option to limit listing all movies/series

### ISSUE THREAD

**Issue by sevospl** [Waterboy1602/Addarr#85]
Hi there.

There should be an option to limit the listing of movies/series to admins only.

I haven't looked through the code yet and checked whether a response is cached in the first place
but it seems like you can flood the bot with this command and there's no throttle whatsoever.

**Comment by Waterboy1602** [comment]
Added to the latest release [V0.6](https://github.com/Waterboy1602/Addarr/releases/tag/V0.6)
