### ISSUE TITLE
Figure out *arr profile ID by its name

### ISSUE THREAD

**Issue by sevospl** [Waterboy1602/Addarr#87]
Hi there.

I suggest to not rely on quality profile IDs as users may have multiple quality profiles and IDs may also not be consistent (e.g. because of modifying profiles).

Radarr/Sonarr lets you fetch a list of existing profiles so it would probably
be trivial to compare the user's input (e. g. "HD - 720p/1080p") with what the *arr's API response includes.

**Comment by Waterboy1602** [comment]
Added to the latest release [V0.6](https://github.com/Waterboy1602/Addarr/releases/tag/V0.6)
