### ISSUE TITLE
Adding series broken due to Sonarr V3 api upgrade

### ISSUE THREAD

**Issue by fidelix** [Waterboy1602/Addarr#88]
Log from Sonarr when adding series:

```
Invalid request Validation failed: 
 -- LanguageProfileId: Language profile does not exist
```

I already have 2 language profiles. I also tried removing the language profiles.

Some info available here:
https://github.com/l3uddz/traktarr/issues/80

**Comment by fidelix** [comment]
I simply undid these changes and everything now works again:
https://github.com/Waterboy1602/Addarr/commit/d121304c41ca9147eaa566c64e19b79a35e9cda3

So it's definitely due to v3 upgrade.

**Comment by Waterboy1602** [comment]
Should be fixed by this commit. Now you'll have to define the `languageProfileId` in the configs. The default value is 1: `All languages`.
