### ISSUE TITLE
Can't add bot to group chat?

### ISSUE THREAD

**Issue by BusterBlex** [Waterboy1602/Addarr#90]
Hi, 

Complete noob here but I have successfully got addarr up and running, however when I add the bot to a group chat, despite the password being correct the bot says I have the incorrect password. I haven't had this issue when interacting with just the bot but seem to have hit a wall trying to resolve it.

Again I am very new to this so it may be an obvious answer or not possible. 

Cheers

**Comment by BusterBlex** [comment]
Never mind, just got it working haha

**Comment by heisenberg2980** [comment]
Just tried adding the bot to a group and I realised all messages need to start with "/" for them to work (including the name of the movies/series), @BusterBlex are you experiencing the same?
