### ISSUE TITLE
No results found when searching Sonarr

### ISSUE THREAD

**Issue by BusterBlex** [Waterboy1602/Addarr#91]
Hi, 

I have Addarr configured and working with radarr but for some reason sonarr is returning no results. 

21-11-30 12:15:12.8|Trace|Http|Req: 311 [GET] /api/v3/series/lookup?apikey=(removed)&term=Dexter
21-11-30 12:15:12.8|Trace|Http|Res: 311 [GET] /api/v3/series/lookup?apikey=(removed)&term=Dexter: 404.NotFound (2 ms)
21-11-30 12:15:12.8|Debug|Api|[GET] /api/v3/series/lookup?apikey=(removed)&term=Dexter: 404.NotFound (2 ms)

**Comment by Waterboy1602** [comment]
Do you already have Sonarr V3? Otherwise I can't think of any reason why you get that error on Sonarr.

**Comment by BusterBlex** [comment]
User error, I had not upgraded to v3. Resolved now
