### ISSUE TITLE
Feature request: select Quality Profiles

### ISSUE THREAD

**Issue by campodoro74** [Waterboy1602/Addarr#92]
Excellent work, me and my friends love Addarr - doing it's job perfectly. 

We do request if it would be possible to select the Quality / Language Profile (as we have 5 languages on our system). 
We can already select the proper Language folder, that's great !

Thank you!

**Comment by Waterboy1602** [comment]
Added to the latest release [V0.6](https://github.com/Waterboy1602/Addarr/releases/tag/V0.6)
